version: '3.8'

services:
  spider:
    build: .
    container_name: tvpl_spider
    depends_on:
      - mongodb
    environment:
      - MONGODB_HOST=mongodb
    volumes:
      - ./data:/app/data
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

networks:
  default:
    name: tvpl_network